name: Salesforce CI Pipeline

on:
  push:
    branches: [ main ]

jobs:
  salesforce-ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Salesforce CLI
        run: |
          npm install @salesforce/cli --global
          sf --version

      - name: Validate setup
        run: echo "Salesforce CLI installed successfully"