name: Salesforce CI/CD Pipeline

on:
  pull_request:
    branches: [ main ]

jobs:
  validate-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Salesforce CLI
        run: |
          npm install @salesforce/cli --global
          sf --version

      - name: Authenticate to Salesforce
        run: |
          echo "${{ secrets.SF_AUTH_URL }}" > auth.txt
          sf org login sfdx-url -f auth.txt -s -a DevOrg

      # ---------------- CI PART ----------------
      - name: Run Apex Tests (CI)
        run: |
          sf apex run test --result-format human --wait 10

      # ---------------- CD PART ----------------
      - name: Validate Deployment (CD - SAFE)
        run: |
          sf project deploy validate \
            --source-dir force-app \
            --target-org DevOrg \
            --test-level RunLocalTests