name: Salesforce CI Pipeline

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Salesforce CLI
        run: npm install @salesforce/cli --global

      - name: Check CLI version
        run: sf --version